urdf_trex:
    # Publish joint states
    #Publishes the joint state to the ROS topics
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # Sets the controller gains for the arm joints
    trex_arm_controller:
        type: effort_controllers/JointTrajectoryController
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4

        constraints:
            goal_time: 0.5                   # Override default
            stopped_velocity_tolerance: 0.02 # Override default
            joint_1:
                trajectory: 1.0               # Not enforced if unspecified
                goal: 0.5                     # Not enforced if unspecified
            joint_2:
                trajectory: 1.0               # Not enforced if unspecified
                goal: 0.5                     # Not enforced if unspecified
            joint_3:
                trajectory: 1.0               # Not enforced if unspecified
                goal: 0.5                     # Not enforced if unspecified
            joint_4:
                trajectory: 1.0               # Not enforced if unspecified
                goal: 0.5                     # Not enforced if unspecified

        gains:
            joint_1: {p: 1000, i: 0.1, d: 0.01}
            joint_2: {p: 1000, i: 0.1, d: 0.01}
            joint_3: {p: 1000, i: 0.1, d: 0.01}
            joint_4: {p: 1000, i: 0.1, d: 0.01}

# To remove (link_4;link_5) shaking, I tuned the PID values to {p: 1000, i: 0.1, d: 1}


    